deploy:
  - provider: releases
    api_key:
      secure: "iFpUAG1J8pnxL/lyIm4t18gQx0OaajpXWSEIQr0QeiKFKAj5mZ0rTr4XD4ditLKZ7Ar/ZcPlD+wJ6k4MEVjrkDs+SxSgMKoygXIu35m4pxNpUNPbyR1q0etfpnyMWr7KZWPhqzQw4FbQgAdNvA4l0CQi9ufaFIzE0gZl/uKW+CJbjRp+VrFKSeK1BuUSrjzS9iwwPy4DnxzOxmA8d3PLj/BCmh+rdjLHvdEAdVO5mRn6h2uTOTYsrYY+QBgI0Ibi1oiy6hkrW5snqEpaeg5w5fbcI9zds3QXWJucQSjBF8EFVgwcHHDM1Z339pnxbYHWZg683Q9tMjpUhgrc+CJxVW1O+vUaVkCa/6Js8B46RwgpZmBOWotxvYFfL/sxrvhh7mxnl/KSAHxMJ1NoReaS8SLBHqQu12/jyOQlblj+/jB/P/jAoj8R7S2p83FyNNuTg22zEV7oXIruaEsz4qfMNPR3RfVOTYzvKZPq6II67lHd5qNjAWNLpeDisBqHQ8dmE53Q10DtCLbzvzlLHbLtFExYToG1vwWNoe641vCa/ZEII2e0t0+tRIdXJ80Jgt2hHdTPpng0Xgsthf05SCwi2A9p0exVJt95ty7kEEUrpUZ9yEGFyO7H3kDvK7gk345BsMo7wIpoXgpp4uRwHy1Ylw3ZJPZG/J8Ju2D1eHtbF5Y="
    file:
      - app.js
    skip_cleanup: true
    overwrite: true
    on:
      repo: zhaoqin-github/sample-repo
      tags: true
